<Project Sdk="Microsoft.NET.Sdk">

  <!-- Camada de infraestrutura do Cart: armazenamento em Redis. -->

  <ItemGroup>
    <ProjectReference Include="..\Cart.Application\Cart.Application.csproj" />
    <ProjectReference Include="..\Cart.Domain\Cart.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Marketplace.Infrastructure\Marketplace.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

</Project>
