<Project Sdk="Microsoft.NET.Sdk">

  <!-- Camada de infraestrutura do Payment: conexao Redis para idempotencia. -->

  <ItemGroup>
    <ProjectReference Include="..\Payment.Application\Payment.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Marketplace.Infrastructure\Marketplace.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

</Project>
