<Project Sdk="Microsoft.NET.Sdk">

  <!-- Camada de aplicacao do Cart: comandos e consultas do carrinho. -->

  <ItemGroup>
    <ProjectReference Include="..\Cart.Domain\Cart.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Marketplace.Application\Marketplace.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
