namespace Identity.Application.Models;

/// <summary>
/// Represents the pair of access and refresh tokens generated by the authentication service.
/// </summary>
/// <param name="AccessToken">The JWT access token.</param>
/// <param name="AccessTokenExpiresAtUtc">The UTC expiration timestamp of the access token.</param>
/// <param name="RefreshToken">The opaque refresh token.</param>
/// <param name="RefreshTokenExpiresAtUtc">The UTC expiration timestamp of the refresh token.</param>
public sealed record TokenPair(string AccessToken, DateTime AccessTokenExpiresAtUtc, string RefreshToken, DateTime RefreshTokenExpiresAtUtc);