<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- Camada de apresentacao do Cart. -->

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cart.Application\Cart.Application.csproj" />
    <ProjectReference Include="..\Cart.Infrastructure\Cart.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Marketplace.Infrastructure\Marketplace.Infrastructure.csproj" />
  </ItemGroup>

</Project>
