<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- Host do Payment: apenas consumidores de fila e health checks. -->

  <ItemGroup>
    <PackageReference Include="MassTransit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payment.Application\Payment.Application.csproj" />
    <ProjectReference Include="..\Payment.Infrastructure\Payment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Marketplace.Infrastructure\Marketplace.Infrastructure.csproj" />
  </ItemGroup>

</Project>
